### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by joshnishikawa** [arduino/library-registry#2268]
### Library name

MIDIcontroller

### Version to remove

2.5.6

**Comment by per1234** [comment]
Hi @joshnishikawa. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Done:
```
2022/12/22 11:05:06 Loaded 5440 libraries from DB
Removing MIDIcontroller@2.5.6
Success!
```

**Comment by joshnishikawa** [comment]
Version 2.5.6 is still showing up in the library manager but version 2.5.5 is not. Version 2.5.5 is the latest stable version. Version 2.5.6 is broken. Since the IDE kindly lets users know when there's an update, it would be nice if the latest version was one that works. I'm not sure why 2.5.5 isn't getting picked up. Thanks for any help.

**Comment by per1234** [comment]
Hi @joshnishikawa.

> Version 2.5.6 is still showing up in the library manager

I see the problem here:

https://github.com/joshnishikawa/MIDIcontroller/blob/2.5.5/library.properties#L2

```text
version=2.5.6
```

The unit of release of Arduino Library Managers is the Git tag, but tags only serve as the markers for each release in the repository. After checking out each tag, the "engine" tool that generates the Library Manager data gets all information about the release from the library contents. So the tag is significant, but the name of the tag is completely ignored. The version of the release is determined by the `version` field in the `library.properties` metadata file.

For some reason you had the value of the `version` field set to `2.5.6` at the time you created the `2.5.5` tag.

The "engine" tool adds all compliant tags present in each of the library repository to the Library Manager index each hour, so even though **unbynos** removed the 2.5.6 release from the index, it was just added back in an hour later due to that release still being tagged in the repository. When you submitted the request, I checked to see whether you had deleted the tag for the 2.5.6 release, but I looked for a tag named 2.5.6 and assumed the absence meant you had removed the tag.

I'll reopen the issue so we can track the need to handle your request, but before we can do that you will need to delete the tag for the 2.5.6 release. I'll provide instructions you can follow to do that:

1. Click the following link to open the GitHub page of the tag:
   https://github.com/joshnishikawa/MIDIcontroller/releases/tag/2.5.5
1. Click the <kbd>**Delete**</kbd> button on that page.
1. Click the <kbd>**I understand, delete this tag**</kbd> button.
1. Comment here to let me know that the tag has been deleted so that I can proceed with removing the release from Arduino Library Manager. 

>I'm not sure why 2.5.5 isn't getting picked up.

There is no 2.5.5 release of the library because there is no tag in your repository where the `version` field in `library.properties` is set to `2.5.5`.

**Comment by joshnishikawa** [comment]
I see. I should have known I had some wires crossed getting this release out. The link takes me to the page for the 2.5.5 release. The 2.5.6 tag doesn't actually exist anymore but Indeed, if I click on the 2.5.5 tag, it takes me to a version of the repo where library.properties says 2.5.6. I assumed I just needed to delete the entire 2.5.5 release and republish after 2.5.6 disappears. So I've done that. Now there should be no releases or tags for 2.5.5 or 2.5.6. Thanks for looking into this.

**Comment by per1234** [comment]
OK, I verify the library repository is now configured for a persistent removal of the 2.5.6 release. As before, this is a manual process so the request will take some time to be accomodated, but no further action is needed on your part.

Please let me know if you have any questions or concerns.

Regards,
Per

**Comment by joshnishikawa** [comment]
I deleted the 2.5.6 tag a couple of weeks ago. This thread still has a "waiting for information" label. Do I need to do anything else?

**Comment by per1234** [comment]
>This thread still has a "waiting for information" label.

No, that label was removed as soon as you resolved the outstanding task two weeks ago. You are probably seeing the label removal action item GitHub added to the thread when I did that.

>Do I need to do anything else?

No, everything is taken care of on your end. Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done.

So the delay before the library is added is dependent on what point in the cycle your request happened to fall. You can follow the issue/PRs to receive a notification from GitHub when it is closed. After that, there may be a delay of some hours for the library's releases to be picked up by the indexer and for the updates to the [Library Manager index](http://downloads.arduino.cc/libraries/library_index.json) to propagate through the CDN cache.

We'll surely get to it soon, please be patient.

**Comment by MatteoPologruto** [comment]
Done:
```
2023/01/25 16:59:56 Loaded 5514 libraries from DB
Removing MIDIcontroller@2.5.6
Success!
```
