### ISSUE TITLE
Library name change request

### ISSUE THREAD

**Issue by jonnybergdahl** [arduino/library-registry#3561]
### Library repository URL

https://github.com/jonnybergdahl/Bergdahl_JBLogger

**Comment by jonnybergdahl** [comment]
I have renamed the the library to JBLogger and moved it to a new repo: 
https://github.com/jonnybergdahl/Arduino_JBLogger_Library

The old repo is gone.

**Comment by per1234** [comment]
Hi @jonnybergdahl. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by MatteoPologruto** [comment]
Done:
```
2023/11/08 14:48:48 Loaded 6352 libraries from DB
Removing Bergdahl_JBLogger
Success!
```

**Comment by jonnybergdahl** [comment]
How long does it take to show up here: https://www.arduino.cc/reference/en/libraries ??
I still see the old name - https://www.arduino.cc/reference/en/libraries/bergdahl_jblogger/

**Comment by per1234** [comment]
Hi @jonnybergdahl. Unfortunately I don't have an answer for that. Although the Arduino Library Reference is built from the data in [the Arduino Library Manager index](https://downloads.arduino.cc/libraries/library_index.json), which is in turn built from the data in this repository, I don't have any involvement in the closed source system that generates and publishes the Arduino Library Reference project so I don't know what the update schedule is on that.

If you would like to get an answer to that question, you can send a request to Arduino technical support via this form:

https://www.arduino.cc/en/contact-us

They should be able to get an answer from the people who do maintain that system.
